plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/burko/Desktop/vent-b2b-gtm/sun-izakaya"
publishOrigin = "default"
base = "/Users/burko/Desktop/vent-b2b-gtm/sun-izakaya"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]